name:                cacheperf
version:             0.1.0.0
github:              "CthulhuDen/cacheperf"
license:             BSD3
author:              "Cthulhu"
maintainer:          "cthulhu.den@gmail.com"
copyright:           "Cthulhu (c) 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CthulhuDen/cacheperf#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -O2

library:
  source-dirs: src
  dependencies:
  - unliftio-core

executables:
  cacheperf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cacheperf
    - unliftio
    - wai
    - warp
    - http-types
    - bytestring

tests:
  cacheperf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cacheperf
